CREATE TABLE playlistref (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  song INTEGER NOT NULL,
  playlist INTEGER NOT NULL,
  last_updated INTEGER NOT NULL,
  FOREIGN KEY(playlist) REFERENCES playlists(id) ON DELETE CASCADE,
  FOREIGN KEY(song) REFERENCES songs(id) ON DELETE CASCADE,
  CONSTRAINT UQ_playlist_song UNIQUE (playlist, song)
)