CREATE TABLE songs (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  genre INTEGER NULL,
  artist INTEGER NULL,
  album INTEGER NULL,
  cover INTEGER NULL,
  title VARCHAR NOT NULL,
  release INTEGER NULL,
  trackno INTEGER NULL,
  metatags TEXT NOT NULL,
  buffer BLOB NOT NULL UNIQUE,
  last_updated INTEGER NOT NULL,
  FOREIGN KEY(genre) REFERENCES genre(id) ON DELETE SET NULL,
  FOREIGN KEY(artist) REFERENCES artists(id) ON DELETE SET NULL,
  FOREIGN KEY(album) REFERENCES albums(id) ON DELETE SET NULL,
  FOREIGN KEY(cover) REFERENCES images(id) ON DELETE SET NULL
)