CREATE TABLE artists (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  name VARCHAR NOT NULL UNIQUE,
  image INTEGER NULL,
  last_updated INTEGER NOT NULL,
  FOREIGN KEY (image) REFERENCES images(id)
)