CREATE TABLE features (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  artist INTEGER NOT NULL,
  song INTEGER NOT NULL,
  last_updated INTEGER NOT NULL,
  FOREIGN KEY(artist) REFERENCES artists(id) ON DELETE CASCADE,
  FOREIGN KEY(song) REFERENCES songs(id) ON DELETE CASCADE,
  CONSTRAINT UQ_artist_song UNIQUE (artist, song)
)